### PR TITLE
Fix an AIOOB exception due to bad setting of chunk sizes

### LINKED ISSUE #286: AIOOB Exception in ConnectedComponents
**Describe the bug**
Running _Purify_ or _Analyse Particles_ on images with the 'wrong' number of slices leads to an AIOOB exception thrown from threads running on the 'big' chunk & slice numbers:
```
Exception in thread "Thread-198311" Exception in thread "Thread-198309" Exception in thread "Thread-198310" Exception in thread "Thread-198312" java.lang.ArrayIndexOutOfBoundsException: 407
	at org.bonej.plugins.ConnectedComponents.lambda$firstIDAttribution$1(ConnectedComponents.java:266)
	at java.lang.Thread.run(Thread.java:748)
java.lang.ArrayIndexOutOfBoundsException: 401
	at org.bonej.plugins.ConnectedComponents.lambda$firstIDAttribution$1(ConnectedComponents.java:300)
	at java.lang.Thread.run(Thread.java:748)
java.lang.ArrayIndexOutOfBoundsException: 418
	at org.bonej.plugins.ConnectedComponents.lambda$firstIDAttribution$1(ConnectedComponents.java:266)
	at java.lang.Thread.run(Thread.java:748)
java.lang.ArrayIndexOutOfBoundsException: 429
	at org.bonej.plugins.ConnectedComponents.lambda$firstIDAttribution$1(ConnectedComponents.java:266)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-198351" java.lang.ArrayIndexOutOfBoundsException: 418
	at org.bonej.plugins.ConnectedComponents.lambda$firstIDAttribution$2(ConnectedComponents.java:427)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-198350" Exception in thread "Thread-198352" java.lang.ArrayIndexOutOfBoundsException: 407
	at org.bonej.plugins.ConnectedComponents.lambda$firstIDAttribution$2(ConnectedComponents.java:427)
	at java.lang.Thread.run(Thread.java:748)
java.lang.ArrayIndexOutOfBoundsException: 429
	at org.bonej.plugins.ConnectedComponents.lambda$firstIDAttribution$2(ConnectedComponents.java:427)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-198390" Exception in thread "Thread-198389" java.lang.ArrayIndexOutOfBoundsException: 407
	at org.bonej.plugins.ConnectedComponents.lambda$applyLUT$3(ConnectedComponents.java:657)
	at java.lang.Thread.run(Thread.java:748)
java.lang.ArrayIndexOutOfBoundsException: 401
	at org.bonej.plugins.ConnectedComponents.lambda$applyLUT$3(ConnectedComponents.java:657)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-198391" java.lang.ArrayIndexOutOfBoundsException: 418
	at org.bonej.plugins.ConnectedComponents.lambda$applyLUT$3(ConnectedComponents.java:657)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-198550" java.lang.ArrayIndexOutOfBoundsException: 407
	at org.bonej.plugins.ConnectedComponents.lambda$firstIDAttribution$1(ConnectedComponents.java:344)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-198551" java.lang.ArrayIndexOutOfBoundsException: 418
	at org.bonej.plugins.ConnectedComponents.lambda$firstIDAttribution$1(ConnectedComponents.java:344)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-198549" java.lang.ArrayIndexOutOfBoundsException: 401
	at org.bonej.plugins.ConnectedComponents.lambda$firstIDAttribution$1(ConnectedComponents.java:373)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-198552" java.lang.ArrayIndexOutOfBoundsException: 429
	at org.bonej.plugins.ConnectedComponents.lambda$firstIDAttribution$1(ConnectedComponents.java:344)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-198590" Exception in thread "Thread-198591" Exception in thread "Thread-198592" java.lang.ArrayIndexOutOfBoundsException: 418
	at org.bonej.plugins.ConnectedComponents.lambda$firstIDAttribution$2(ConnectedComponents.java:442)
	at java.lang.Thread.run(Thread.java:748)
java.lang.ArrayIndexOutOfBoundsException: 407
	at org.bonej.plugins.ConnectedComponents.lambda$firstIDAttribution$2(ConnectedComponents.java:442)
	at java.lang.Thread.run(Thread.java:748)
java.lang.ArrayIndexOutOfBoundsException: 429
	at org.bonej.plugins.ConnectedComponents.lambda$firstIDAttribution$2(ConnectedComponents.java:442)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-198629" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "Thread-198630" Exception in thread "Thread-198631" java.lang.ArrayIndexOutOfBoundsException: 407
	at org.bonej.plugins.ConnectedComponents.lambda$applyLUT$3(ConnectedComponents.java:657)
	at java.lang.Thread.run(Thread.java:748)
java.lang.ArrayIndexOutOfBoundsException: 418
	at org.bonej.plugins.ConnectedComponents.lambda$applyLUT$3(ConnectedComponents.java:657)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-198830" Exception in thread "Thread-198832" Exception in thread "Thread-198831" java.lang.ArrayIndexOutOfBoundsException: 429
	at org.bonej.plugins.ConnectedComponents.lambda$firstIDAttribution$1(ConnectedComponents.java:266)
	at java.lang.Thread.run(Thread.java:748)
java.lang.ArrayIndexOutOfBoundsException: 407
	at org.bonej.plugins.ConnectedComponents.lambda$firstIDAttribution$1(ConnectedComponents.java:266)
	at java.lang.Thread.run(Thread.java:748)
java.lang.ArrayIndexOutOfBoundsException: 418
	at org.bonej.plugins.ConnectedComponents.lambda$firstIDAttribution$1(ConnectedComponents.java:266)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-198829" java.lang.ArrayIndexOutOfBoundsException: 402
	at org.bonej.plugins.ConnectedComponents.lambda$firstIDAttribution$1(ConnectedComponents.java:300)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-198872" java.lang.ArrayIndexOutOfBoundsException: 429
	at org.bonej.plugins.ConnectedComponents.lambda$firstIDAttribution$2(ConnectedComponents.java:427)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-198870" Exception in thread "Thread-198871" java.lang.ArrayIndexOutOfBoundsException: 407
	at org.bonej.plugins.ConnectedComponents.lambda$firstIDAttribution$2(ConnectedComponents.java:427)
	at java.lang.Thread.run(Thread.java:748)
java.lang.ArrayIndexOutOfBoundsException: 418
	at org.bonej.plugins.ConnectedComponents.lambda$firstIDAttribution$2(ConnectedComponents.java:427)
	at java.lang.Thread.run(Thread.java:748) 
```

**To Reproduce**
run this macro:
```java
setBatchMode(true);  
for (i = 1; i <= 1000; i++){
  print("Purifying image with "+i+" slices");
  newImage("Untitled", "8-bit noise", 64, 64, i);
  setThreshold(0, 127);
  setOption("BlackBackground", false);
  run("Convert to Mask", "method=Default background=Dark");
  run("Purify", " ");
  close();
}
```
**Expected behavior**
The plugin completes without throwing an exception

**Diagnosis**
The lines throwing an exception are all referencing a _z_ value, and are more than `nSlices`. This is a bug in the way the start slice numbers are calculated and distributed to threads.

### PR DESCRIPTION
**Pull request by mdoube**
This approach to setting chunk sizes no longer throws an AIOOB, but does
mean that the last chunk can be larger than the rest on big stacks.

Fixes #286

### CODE REVIEW

**Comment by alessandrofelder** [comment]
Hmm, I can't reproduce the error on my machine, and I can't think of a situation where an entry in `startSlices` would be larger than `nSlices` in the olde code after spending an hour trying to figure it out. 

My best guess is that it's some kind of numerical precision issue where `ceil` gives something unexpected (like `ceil((double) 80/ (double) 8)` giving `11` because the floating point division gives _slightly_ more than `10`) but I can't think of a concrete situation where that would cause problems in the old code. The worry here for me is therefore that we haven't identified the root cause, and there might be other situations that we're not covering with the change that will cause the same AIOOB?

**Comment by mdoube** [comment]
> Hmm, I can't reproduce the error on my machine using the Macro in the issue, and I can't think of a situation where an entry in `startSlices` would be larger than `nSlices` in the olde code after spending an hour trying to figure it out.

Thanks for taking a look. On my machine I have 40 CPU threads so that may have exposed it.
For a 401-slice image the old code goes like:
```java
    //minSlicesPerChunk = 10 (hard coded) and nProcessors = 40
    //ternary evaluates to false so nChunks = nProcessors = 40
    final int nChunks = nSlices < minSlicesPerChunk * nProcessors
				? (int) Math.ceil((double) nSlices / (double) minSlicesPerChunk)
				: nProcessors;
		// set up chunk sizes - last chunk is the remainder
      // slicesPerChunk = nSlices 401.0 / nChunks 40.0 = 10.025 rounded up by Math.ceil() to 11
		final int slicesPerChunk = (int) Math.ceil((double) nSlices / (double) nChunks);

//later on we set up an array using the values above
// set up start slice array
//startSlices[] has nChunks = 40 elements' length
		final int[] startSlices = new int[nChunks];
		for (int i = 0; i < nChunks; i++) {
//now i iterates and multiplies by slicesPerChunk, 11
			startSlices[i] = i * slicesPerChunk;
//this is fine until the last few elements because startSlices[37] is assigned 37 * 11 = 407
//which means that there are startSlices in the list that do not exist in the image array, which has only 401 slices
//causing the later AIOOB.
		}
``` 
The bug appears only on some combinations of `nProcessors` and `nSlices`, which may be why it's hard to reproduce, but I am confident that it does exist and that I have diagnosed and fixed it correctly.

**Comment by alessandrofelder** [comment]
Perfect, thank you - that explanation makes sense to me now.

File: Legacy/bonej/src/main/java/org/bonej/plugins/ConnectedComponents.java [hunk 1]
```diff
@@ -115,13 +115,20 @@ public ConnectedComponents() {
...
+		if (nSlices < minSlicesPerChunk) {
+			slicesPerChunk = nSlices;
+			nChunks = 1;
+		} else if (nSlices <= minSlicesPerChunk * nProcessors) {
+			slicesPerChunk = minSlicesPerChunk;
+			nChunks = (int) Math.ceil((double) nSlices / (double) minSlicesPerChunk); 
+		} else if (nSlices > minSlicesPerChunk * nProcessors) {
+			nChunks = nProcessors;
+			slicesPerChunk = (int) Math.floor((double) nSlices / (double) nChunks);
+		}
```
Comment (alessandrofelder) [inline Legacy/bonej/src/main/java/org/bonej/plugins/ConnectedComponents.java:130]: This comment can be ignored, but I wanted to flag that it was unintuitive for me that the first two `if` clauses assign `slicePerChunk` first, and the third clause does the opposite, just in terms of the flow of reading a piece of code I had never looked at before. Might be worth swapping the order in the first two clauses. But again, happy to leave it :)

**Review by alessandrofelder — APPROVED** [review]
Happy with this.
Thanks for taking the time to explain further when I didn't get it.
